version: '3'

services:
  pjecalc:
    image: tomcat:8-jre8
    container_name: pjecalc
    restart: always
    ports:
      - "9256:9256"
      - "9257:9257"
      - "9258:9258"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./.dados:/opt/pjecalc/.dados
    environment:
      - JAVA_OPTS=-Duser.timezone=GMT-3 -Dfile.encoding=ISO-8859-1 -Dseguranca.pjecalc.tokenServicos=pW4jZ4g9VM5MCy6FnB5pEfQe -Dseguranca.pjekz.servico.contexto=https://pje.trtXX.jus.br/pje-seguranca -Xms1024m -Xmx2048m
    command: >
      bash -c "sed -i 's/port=\"8080\"/port=\"9257\"/' /usr/local/tomcat/conf/server.xml &&
               sed -i 's/port=\"8005\"/port=\"9256\"/' /usr/local/tomcat/conf/server.xml &&
               sed -i 's/port=\"8009\"/port=\"9258\"/' /usr/local/tomcat/conf/server.xml &&
               catalina.sh run"
